sot_controller:
  libname: libsot-tiago-steel-controller.so
  map_rc_to_sot_device: { motor-angles: motor-angles ,
  joint-angles: joint-angles, velocities: velocities, forces: forces, currents: currents,
  torques: torques, accelerometer_0: accelerometer_0, gyrometer_0: gyrometer_0,
  control: control
  }
  control_mode:
    torso_lift_joint:
      ros_control_mode: POSITION
    arm_1_joint:
      ros_control_mode: POSITION
    arm_2_joint:
      ros_control_mode: POSITION
    arm_3_joint:
      ros_control_mode: POSITION
    arm_4_joint:
      ros_control_mode: POSITION
    arm_5_joint:
      ros_control_mode: POSITION
    arm_6_joint:
      ros_control_mode: POSITION
    arm_7_joint:
      ros_control_mode: POSITION
    head_1_joint:
      ros_control_mode: POSITION
    head_2_joint:
      ros_control_mode: POSITION

    gripper_finger_joint:
      ros_control_mode: POSITION

    hand_thumb_joint:
      ros_control_mode: POSITION
    hand_index_joint:
      ros_control_mode: POSITION
    hand_mrl_joint:
      ros_control_mode: POSITION

  dt: 0.01
  jitter: 0.004
